---
version: "3.9"

services:
  sciml-service:
    container_name: sciml-service
    image: ghcr.io/darpa-askem/sciml-service:latest
    ports:
      - "8080:8080"
    environment:
      SIMSERVICE_TDS_URL: "http://hmi-server:3000"
      SIMSERVICE_TDS_USER: "api-service"
      SIMSERVICE_TDS_PASSWORD: "agent bio terraform"
      SIMSERVICE_RABBITMQ_ENABLED: "false"
      SIMSERVICE_RABBITMQ_LOGIN: "terarium"
      SIMSERVICE_RABBITMQ_PASSWORD: "terarium123"
      SIMSERVICE_RABBITMQ_ROUTE: "sciml-queue"
      SIMSERVICE_RABBITMQ_HOST: "rabbitmq"
      SIMSERVICE_RABBITMQ_PORT: "5672"
      SIMSERVICE_RABBITMQ_SSL: "false"
    depends_on:
      rabbitmq:
        condition: service_started
      hmi-server:
        condition: service_started
    healthcheck:
      test: curl http://localhost:8080/ || exit 1
      interval: 10s
      timeout: 20s
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pyciemss-api:
    container_name: pyciemss-api
    image: ghcr.io/darpa-askem/pyciemss-api:latest
    ports:
      - "8000:8000"
    environment:
      TDS_URL: "http://hmi-server:3000"
      TDS_USER: "api-service"
      TDS_PASSWORD: "agent bio terraform"
      STANDALONE_MODE: "False"
      PYCIEMSS_OUTPUT_FILEPATH: "result.csv"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_started
      hmi-server:
        condition: service_started
    healthcheck:
      test: curl http://localhost:8000/ || exit 1
      interval: 10s
      timeout: 20s
      retries: 30
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pyciemss-worker:
    container_name: pyciemss-worker
    image: ghcr.io/darpa-askem/pyciemss-worker:latest
    environment:
      TDS_URL: "http://hmi-server:3000"
      TDS_USER: "api-service"
      TDS_PASSWORD: "agent bio terraform"
      STANDALONE_MODE: "False"
      PYCIEMSS_OUTPUT_FILEPATH: "result.csv"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      redis:
        condition: service_started
      hmi-server:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
